package pl.datingSite.enums;

public enum MovieType {
    COMEDY, ROMANTIC_COMEDY, SCIENCE_FICTION, FANTASY, ROMANCE, HISTORICAL,
    HORROR, PSYCHOLOGICAL, FANTASTIC, ADVENTURE, THRILLER, TRAVEL, ANIMATED,
    MELODRAMA, COSTUME, FAMILY, MUSICAL, POPULAR_SCIENCE,
    DRAMA, SENSATION, DOCUMENTARY, AUTOMOTIVE
}
